

project:
  type: website

website:
  title: "Luyao Liu"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Marketing Analytics
        file: Marketing.qmd
      - text: Digital Marketing
        file: digital marketing.qmd
      - text: Resume
        file: resume.qmd

format:
  html:
    theme: cosmo
